const devNum = 0;
const url = ['https://nongnghiep.csctech.vn', 'http://appcsc.csctech.vn:81'];
const webUrl = ['https://nongnghiep.csctech.vn', 'http://appcsc.csctech.vn:81'];
module.exports = {
  PRODUCTION: !__DEV__,
  API_URL: url[devNum],
  glob: null,
  prevParticipantId: null,
  AES_KEY: 'C0nt3ntManag3m3ntSyst3m_hgt!16kl',
  accessToken: '',
  userProfile: null,
  DeviceID: null,
  // RootId: '7c01146a-341d-7f19-2132-39fdb4e5e36a',
  // GoogleMapApiKey: 'AIzaSyCUt0Kgv2KzM0xGLot6rnzOIyJHhbT6L9w',
  GoogleNotifyToken: '',
  AssetLinkUrl: webUrl[devNum] + '/data/',
  WebviewUrl: webUrl[devNum],
  RoleName: [],
  MenuRole: [],
  currentScreen: 'Home',
  globalParams: null,
  UserId: null,
  AppInfomations: null,
  updateVersionAppName: 'SkinCheck',
  logAPI: true,
  apiTauCa: 'https://tauca.nongnghiepcamau.vn/',
  StaticTokenTauCa: null,
  GGMapKey: 'AIzaSyB6d1RChRI3DvRkoLKbdNUBVCFOkgSkoRk',
  menu: null,
  appInfo: null,
  tokenFirebase: null,
  tenThietBi: null,
  province: null,
  userInfo: null,
};
